services:
  db:
    image: ankane/pgvector # https://hub.docker.com/r/ankane/pgvector
    environment:
      POSTGRES_DB: llm_db
      POSTGRES_USER: llm_agent
      POSTGRES_PASSWORD: llm_password
    ports:
      - 5433:5432
    command: postgres -c log_destination=stderr -c log_min_duration_statement=0
