# Generated by Django 4.2.4 on 2023-08-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.TextField()),
                ('message', models.JSONField()),
            ],
            options={
                'db_table': 'message_store',
            },
        ),
    ]
