# Generated by Django 4.2.4 on 2023-10-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("llm", "0002_add_organizationstore")
    ]

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("api_key", models.CharField(max_length=255)),
                ("system_prompt", models.TextField()),
                ("human_prompt", models.TextField()),
            ],
            options={
                "db_table": "organization",
            },
        ),
    ]
