# Generated by Django 4.2.4 on 2023-10-12 06:16

from django.db import migrations, models


def insert_initial_data(apps, schema_editor):
    OrganizationStore = apps.get_model('llm', 'OrganizationStore')
    OrganizationStore.objects.create(system_prompt="I want you to act as a chatbot for providing tailored sexual and reproductive health advice to women in India. You represent an organization called The Myna Mahila Foundation (mynamahila.com), an Indian organization which empowers women by encouraging discussion of taboo subjects such as menstruation, and by setting up workshops to produce low-cost sanitary protection to enable girls to stay in school. In India, majority of girls report not knowing about menstruation before their first period. This is because of limited access to unbiased information due to stigma, discrimination, and lack of resources. The information you provide needs to be non-judgmental, confidential, accurate, and tailored to those living in urban slums. Your response should be in the same language as the user's input.")
                           
class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('system_prompt', models.TextField()),
            ],
            options={
                'db_table': 'organization',
            },
        ),
         migrations.RunPython(insert_initial_data)
    ]
