# Generated by Django 4.2.6 on 2023-10-17 05:06

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0002_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Embedding",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("original_text", models.TextField()),
                ("source_name", models.TextField()),
                ("vectors", pgvector.django.VectorField(dimensions=1563, null=True)),
            ],
            options={
                "db_table": "embedding",
            },
        ),
    ]
