# Generated by Django 4.2.6 on 2023-10-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0004_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("system", "system"),
                            ("user", "user"),
                            ("assistant", "assistant"),
                        ],
                        default="user",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
            ],
            options={
                "db_table": "messages",
            },
        ),
        migrations.DeleteModel(
            name="MessageStore",
        ),
    ]
