# Generated by Django 4.2.6 on 2023-10-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0004_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagestore",
            name="type",
            field=models.CharField(
                choices=[("ai", "ai"), ("human", "human")],
                default="human",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="messagestore",
            name="message",
            field=models.TextField(),
        ),
    ]
