# Generated by Django 4.2.6 on 2023-10-22 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0005_message_delete_messagestore"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="type",
            new_name="role",
        ),
    ]
