# Generated by Django 4.2.6 on 2023-10-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_message_evaluation_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='api_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
