# Generated by Django 4.2.6 on 2023-10-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0008_alter_organization_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='evaluator_prompt',
        ),
        migrations.AddField(
            model_name='organization',
            name='evaluator_prompts',
            field=models.JSONField(null=True),
        ),
    ]
