# Generated by Django 4.2.6 on 2023-12-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0009_remove_organization_evaluator_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="examples_text",
            field=models.TextField(null=True),
        ),
    ]
