# Generated by Django 4.2.6 on 2024-03-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0011_organization_openai_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='num_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
