# Generated by Django 4.2.6 on 2024-04-17 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0013_knowledgecategory_file_embedding_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='knowledge_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='llm.knowledgecategory'),
        ),
    ]
